### ISSUE TITLE
React 16.x PropTypes Breaking Change

### ISSUE THREAD

**Issue by wayofthefuture** [wangzuo/react-input-slider#34]
The PropTypes in the library causing the code to break with React 16.x. PropTypes has been deprecated in favor of another method. Any ideas how I can modify this package to allow it to be compatible with both React 15 and 16? I was thinking to just completely remove the PropTypes and it should work with both versions. Thoughts?

**Comment by smeijer** [comment]
It's not that `PropTypes` has been deprecated, PropTypes is extracted from the `React` scope, into it's own module `prop-types`. `react-input-slider` had already fixed this in `v2`, while we're now at `v4`.

I think https://github.com/wayofthefuture/react-input-moment/issues/4 can be fixed by a update of the `react-input-slider` dependency (as it's still using `1.6.0`). No changes to `react-input-slider` are required.

This issue can be closed. There's nothing wrong with `PropTypes` in the latest version of this library.

**Comment by wayofthefuture** [comment]
Thanks!
